set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ivan-cukic/vim-colors-penultimate'


call vundle#end()            " required
filetype plugin indent on    " required


let g:airline_powerline_fonts = 1
let g:airline_theme='murmur'


syntax on
set t_Co=256
colors penultimate
filetype plugin indent on

