#!/bin/bash

source ../utils.sh

assert_argc_ge $# 1 "file [file ...]"

for file in "$@" ; do
    mkdir -p "$(os_path_par "./$file")"
    copy=$(os_path_abs "./$file")
    patch="$copy.patch"
    if io_is_file "$patch" ; then
        if ! std_ask "overwrite $patch"; then
            continue
        fi
    fi
    cp "$file" "$copy"
    "$EDITOR" "$copy"
    diff -N -U 1 "$file" "$copy" > "$patch"
    rm "$copy"
    log_msg "created patch: $patch"
done
