name: Basic syntax check and tests

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.gitea/workflows/_setup

      - name: Run check
        run: ./check --no-container --strict-warnings
        env:
          SETUP_ALLOW_ROOT: "1"
