name: Basic syntax check and tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.gitea/actions/setup

      - name: Run check
        run: ./check --no-container --strict-warnings
        env:
          SETUP_ALLOW_ROOT: "1"

      - name: Check for failures
        if: ${{ failure() }}
        uses: ${{ vars.ACTIONS_ROOT }}/action-gitea-workflow-error-email@v3
        with:
          smtp-host: ${{ secrets.SMTP_HOST }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SMTP_FROM }}
          to: ${{ secrets.WORKFLOW_ERROR_EMAIL }}

      - name: Save logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            *.log
