name: Full setup check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.gitea/actions/setup

      - name: Run check
        run: ./check
        env:
          SETUP_ALLOW_ROOT: "1"

      - name: Send failure email
        # if: ${{ failure() }}
        uses: https://git.example.com/my-org/action-gitea-workflow-error-email@v1
        with:
          smtp-host: ${{ secrets.SMTP_HOST }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SMTP_FROM }}
          to: ${{ secrets.WORKFLOW_ERROR_EMAIL }}
