name: Full setup check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 6"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.gitea/actions/setup

      - name: Run check
        run: ./check
        env:
          SETUP_ALLOW_ROOT: "1"
