#!/bin/bash

# Make sure user is set so `as_user` works
# This is done in case the script is invoked directly
# and not through `setup --services`
if [ -z $SETUP_USER ]; then
    SETUP_USER=$USER
    curr_dir=$PWD
    cd .. && source utils.sh && cd $curr_dir
fi

stow_args="--no-folding -v"

sudo ln -s $(pwd)/sbin /usr/sbin/dotfiles
sudo stow $stow_args system -t /etc/systemd/system 
sudo stow $stow_args user   -t /etc/systemd/user 

for service in $(read_list "./enabled-system-services.txt"); do
    log::msg "enabling system service: $service"
    if ! sudo systemctl enable --now "$(basename "$service")"; then
        log::err "failed to setup: $service"
    fi
done

for service in $(read_list "./enabled-user-services.txt"); do
    log::msg "enabling user service: $service"
    if ! sudo systemctl --user -M $SETUP_USER@ enable --now "$(basename "$service")"; then
        log::err "failed to setup: $service"
    fi
done

