#!/bin/bash

# Make sure user is set in case the script is invoked directly
# and not through `setup --services`
if [ -z "$SETUP_USER" ]; then
    SETUP_USER=$USER
    curr_dir=$PWD
    cd .. && source utils.sh && cd "$curr_dir"
fi

__dry_run=false
if [ $1 == "--dry" ]; then
    __dry_run=true
fi

if [ ! -d /usr/sbin/dotfiles ]; then
    log::msg "linking sbin to /usr/sbin"
    if ! $__dry_run ; then
        sudo ln -s "$(pwd)/sbin/" /usr/sbin/dotfiles
    fi
fi

for service in $(read_list "./enabled-system-services.txt"); do
    log::msg "enabling system service: $service"
    if ! $__dry_run ; then
        if ! sudo systemctl enable --now "$service"; then
            log::err "failed to setup: $service"
        fi
    fi
done

for service in $(read_list "./enabled-user-services.txt"); do
    log::msg "enabling user service: $service"
    if ! $__dry_run ; then
        if ! sudo systemctl --user -M "$SETUP_USER"@ enable --now "$service"; then
            log::err "failed to setup: $service"
        fi
    fi
done

