#!/bin/bash

# create
tmux new-session -d -s "$SESSION_NAME" -c "${ROOT_DIR:-$HOME}"

# win 1
tmux rename-window -t "$SESSION_NAME":1 ncmpcpp
tmux send-keys -t "$SESSION_NAME":ncmpcpp "mp" C-l Enter A Enter y Enter

# win 2
tmux new-window -t "$SESSION_NAME" -n ramfs -c "/ramfs"

# select 1
tmux select-window -t "$SESSION_NAME":ncmpcpp
