#!/usr/bin/env zsh

##
## Modified .oh-my-zsh official python plugin
##

# Remove python compiled byte-code and mypy/pytest cache in either the current
# directory or in a list of specified directories (including sub directories).
function pyclean() {
    find "${@:-.}" -type f -name "*.py[co]" -delete
    find "${@:-.}" -type d -name "__pycache__" -delete
    find "${@:-.}" -depth -type d -name ".mypy_cache" -exec rm -r "{}" +
    find "${@:-.}" -depth -type d -name ".pytest_cache" -exec rm -r "{}" +
}

## venv settings
: ${PYTHON_VENV_NAME:=venv}

# Array of possible virtual environment names to look for, in order
# -U for removing duplicates
typeset -gaU PYTHON_VENV_NAMES
[[ -n "$PYTHON_VENV_NAMES" ]] || PYTHON_VENV_NAMES=($PYTHON_VENV_NAME .venv venv)

# Activate a virtual environment. If it doesn't exist, create it first.
# With no arguments:
#   - activate the first existing venv in $PYTHON_VENV_NAMES
#   - if none exist, create $PYTHON_VENV_NAME and activate it
function venv() {
    local name venvpath

    if [[ -n "$1" ]]; then
        name="$1"
    else
        for name in $PYTHON_VENV_NAMES; do
            venvpath="${name:P}"
            if [[ -d "$venvpath" ]]; then
                break
            fi
        done

        # No existing venv found; create the default one.
        if [[ -z "$name" || ! -d "${name:P}" ]]; then
            name="$PYTHON_VENV_NAME"
            python3 -m venv "$name" || return $?
            echo "Created virtual environment '$name'"
        fi
    fi

    venvpath="${name:P}"

    if [[ ! -d "$venvpath" ]]; then
        python3 -m venv "$name" || return $?
        echo "Created virtual environment '$name'"
    fi

    if [[ ! -f "$venvpath/bin/activate" ]]; then
        echo >&2 "Error: '$name' is not a proper virtual environment"
        return 1
    fi

    . "$venvpath/bin/activate" || return $?
    echo "Activated virtual environment '$name'"
}

if [[ "$PYTHON_AUTO_VRUN" == "true" ]]; then
    # Automatically activate venv when changing dir
    function auto_vrun() {
        # deactivate if we're on a different dir than VIRTUAL_ENV states
        # we don't deactivate subdirectories!
        if (( $+functions[deactivate] )) && [[ $PWD != ${VIRTUAL_ENV:h}* ]]; then
            deactivate > /dev/null 2>&1
        fi

        if [[ $PWD != ${VIRTUAL_ENV:h} ]]; then
            local file
            for file in "${^PYTHON_VENV_NAMES[@]}"/bin/activate(N.); do
                # make sure we're not in a venv already
                (( $+functions[deactivate] )) && deactivate > /dev/null 2>&1
                source $file > /dev/null 2>&1
                break
            done
        fi
    }
    add-zsh-hook chpwd auto_vrun
    auto_vrun
fi

