#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png

# Use screenshot as a lock screen
scrot -z $PICTURE
# Use wallpaper as a lock screen
# cp $1 $PICTURE

BLUR="5x4"

convert $PICTURE -blur $BLUR $PICTURE
i3lock -i $PICTURE -p default -t
rm $PICTURE
