#!/bin/bash

# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

# Default values
t_warn="${T_WARN:-50}"
t_crit="${T_CRIT:-80}"
cpu_usage=-1
decimals="${DECIMALS:-0}"
label="${LABEL:-}"
label1="${LABEL_1:-}"
label2="${LABEL_2:-}"

# Help function
help() {
    echo "Usage: cpu_usage [-w <warning>] [-c <critical>] [-d <decimals>]"
    echo "-w <percent>: warning threshold to become yellow"
    echo "-c <percent>: critical threshold to become red"
    echo "-d <decimals>: Use <decimals> decimals for percentage (default is $decimals)"
    exit 0
}

# Parse command-line options
while getopts "hw:c:d:" opt; do
    case $opt in
        h) help ;;
        w) t_warn=$OPTARG ;;
        c) t_crit=$OPTARG ;;
        d) decimals=$OPTARG ;;
        *) help ;;
    esac
done

# Get CPU usage
export LC_ALL="en_US.UTF-8"  # Ensure mpstat runs with the correct locale
cpu_usage=$(mpstat 1 1 | awk '/Average/ {print 100 - $12}')  # 100% - %idle
if [ -z "$cpu_usage" ]; then
    echo "Can't find CPU information"
    exit 1
fi

# Get turbo boost information
if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
    boost=$(< /sys/devices/system/cpu/intel_pstate/no_turbo)
    if [ "$boost" == "1" ]; then
        label="$label1"
    else
        label="$label2"
    fi
else
    label="$label2"
fi

# Print short_text and full_text
printf "%s" "$label"
printf "%02.${decimals}f%%\n" "$cpu_usage"
printf "%s" "$label"
printf "%02.${decimals}f%%\n" "$cpu_usage"

# Print color based on thresholds
if (( $(echo "$cpu_usage >= $t_crit" | bc -l) )); then
    echo "#FF0000"  # Critical threshold - Red
elif (( $(echo "$cpu_usage >= $t_warn" | bc -l) )); then
    echo "#FFFC00"  # Warning threshold - Yellow
fi

exit 0
