#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png

# Use screenshot as a lock screen
scrot -z $PICTURE
# Use wallpaper as a lock screen
# cp $1 $PICTURE

# http://www.imagemagick.org/Usage/blur/#blur_args
BLUR="5x3"

magick convert $PICTURE -blur $BLUR - | magick composite -gravity center /usr/share/icons/lock.png - $PICTURE
i3lock -i $PICTURE -t 
rm $PICTURE
