#!/bin/bash

BLOCK_BUTTON=${BLOCK_BUTTON:-$1}
DEFAULT_SOURCE=$(pactl get-default-source)
SOURCE=${SOURCE:-$DEFAULT_SOURCE}
toggled=false

case $BLOCK_BUTTON in
  1|3)
    pactl set-source-mute "$SOURCE" toggle
    toggled=true
    ;;
esac

# Get mute status using wpctl instead of pacmd
MUTED=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -o '\[MUTED\]')

if [ "$MUTED" = "[MUTED]" ]; then
  echo ""
  if $toggled ; then
    notify-send -t 500 "  |  Muted"
  fi
else
  echo ""
  echo ""
  echo "#D21A1A"
  if $toggled ; then
    notify-send -t 500 "  |  Unmuted"
  fi
fi
