#!/bin/bash

# https://github.com/vivien/i3blocks-contrib/blob/master/toggle/toggle
# modified to support different labels

label=''
label_off=''
label_on=''

status=$(mpc status)
is_playing=$(echo $status | grep "\[playing\]")
is_paused=$(echo $status | grep "\[paused\]")
if (( ${BLOCK_BUTTON:-0} == 1 )); then    # left click
  if [ -n "$is_playing" ]; then
    mpc -q pause
    label=$label_off
  else
    mpc -q play
    label=$label_on
  fi
elif (( ${BLOCK_BUTTON:-0} == 2 )); then  # middle click
  mpc -q stop
elif (( ${BLOCK_BUTTON:-0} == 3 )); then  # right click
  mpc -q seek 0%
  label=$label_on
elif (( ${BLOCK_BUTTON:-0} == 4 )); then  # scroll up
  mpc -q next
  label=$label_on
elif (( ${BLOCK_BUTTON:-0} == 5 )); then  # scroll down
  mpc -q prev
  label=$label_on
else
  if [ -n "$is_playing" ]; then
    label=$label_on
  elif [ -n "$is_paused" ]; then
    label=$label_off
  fi
fi

if [ "$label" == '' ]; then
  echo "$label"
else
  echo "$label | $(mpc --format '[[%artist% - ]%title%]|[%file%]' current)"
fi  

