#!/bin/bash

# Wrapper for volume script

v=0
case "$1" in
    up)
        v=4
        ;;
    down)
        v=5
        ;;
    mute)
        v=2
        ;;
    *)
        exit 1
        ;;
esac

BLOCK_BUTTON=$v ${XDG_CONFIG_HOME:-$HOME/.config/i3/scripts/volume} -i ${2:-5} \
    && pkill -RTMIN+10 i3blocks

