#!/usr/bin/env bash

# Note: This script is probably not sourced by i3blocks, check i3blocks config

bg_color=""
color=\#717171
vpnstatus=""

if command -v nordvpn &> /dev/null ; then
    if nordvpn status | grep -q "Status: Connected" ; then
        color=\#15d4ce
        server=$(nordvpn status | grep "Hostname:" | sed -e "s/Hostname: //" | grep -oE "^[^.]+")
        vpnstatus="[$server] "
    fi
else
    bg_color="#ff0000"
fi

echo "$vpnstatus"
echo
echo $color
echo $bg_color
