#!/usr/bin/env bash
#

color=\#717171
vpnstatus=""

nordvpn_output=$(nordvpn status | grep "Status: Connected")
if [ $? -eq 0 ] ; then
    color=\#15d4ce
    server=$(nordvpn status | grep "Current server:" | sed -e "s/Current server: //" | grep -oE "^[^.]+")
    vpnstatus="[$server] "
fi

echo "$vpnstatus"
echo
echo $color
