#!/usr/bin/env bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -x;

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-$(cat /proc/net/wireless | perl -ne '/(\w+):/ && print $1')}"
fi
#------------------------------------------------------------------------

COLOR_GE80=${COLOR_GE80:-#FFFFFF}
COLOR_GE60=${COLOR_GE60:-#94BF19}
COLOR_GE40=${COLOR_GE40:-#C98F1F}
COLOR_LOWR=${COLOR_LOWR:-#DF612A}
COLOR_DOWN=${COLOR_DOWN:-#D21A1A}
LABEL_GE80=${LABEL_GE80:-󰤨}
LABEL_GE60=${LABEL_GE60:-󰤢}
LABEL_GE40=${LABEL_GE40:-󰤟}
LABEL_LOWR=${LABEL_LOWR:-󰤫}
LABEL_DOWN=${LABEL_DOWN:-󰤭}

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo -e "$LABEL_DOWN"
    echo -e "$LABEL_DOWN"
    echo $COLOR_DOWN
    exit 1
fi

#------------------------------------------------------------------------

QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

#------------------------------------------------------------------------

if [ $BLOCK_BUTTON -ne 0 ]; then
    notify-send "$INTERFACE signal strength: $QUALITY%"
fi

# color
if [[ $QUALITY -ge 80 ]]; then
    echo -e "$LABEL_GE80"
    echo -e "$LABEL_GE80"
    echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    echo -e "$LABEL_GE60"
    echo -e "$LABEL_GE60"
    echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    echo -e "$LABEL_GE40"
    echo -e "$LABEL_GE40"
    echo $COLOR_GE40
else
    echo -e "$LABEL_LOWR"
    echo -e "$LABEL_LOWR"
    echo $COLOR_LOWR
fi

