#!/bin/bash

pkgs=(
    retroarch
    retroarch-assets-ozone
    libretro-mame
    libretro-mesen
    libretro-nestopia
    libretro-picodrive
    libretro-retrodream
)
inst "${pkgs[@]}" 
unset pkgs

inst_aur libretro-fbneo

# Download GLSL shaders (as root as it is a global install)
shader_dir=/usr/share/libretro/shaders/glsl-shaders
sudo_git_clone_or_pull https://github.com/libretro/glsl-shaders "$shader_dir"
unset shader_dir
