#!/bin/bash

pkgs=(
    retroarch
    retroarch-assets-ozone
    libretro-mame
    libretro-mesen
    libretro-nestopia
    libretro-picodrive
    libretro-retrodream
)
inst "${pkgs[@]}" 
unset pkgs

inst_aur libretro-fbneo

# Download GLSL shaders (as root as it is a global install)
sudo git clone https://github.com/libretro/glsl-shaders /usr/share/libretro/shaders/glsl-shaders

