#!/bin/bash

if test_installed virtualbox ; then
    log_msg "VirtualBox already installed. Exiting..."
    return
fi

# shellcheck source=/dev/null
source "$(dirname "${BASH_SOURCE[0]}")/linux-headers"
inst virtualbox virtualbox-host-dkms

sudo modprobe vboxdrv vboxnetadp vboxnetflt
