#!/bin/bash

if test::installed virtualbox ; then
    log::msg "VirtualBox already installed. Exiting..."
    return
fi

source ./linux-headers
inst virtualbox virtualbox-host-dkms

sudo modprobe vboxdrv vboxnetadp vboxnetflt

