#!/bin/bash

if test_installed virtualbox ; then
    log_msg "VirtualBox already installed. Exiting..."
    return
fi

source ./linux-headers
inst virtualbox virtualbox-host-dkms

sudo modprobe vboxdrv vboxnetadp vboxnetflt

