#!/bin/bash

source "../utils.sh"

sdk_version=35
emu_device="pixel_7a"

inst_aur android-sdk-cmdline-tools-latest
inst_aur android-sdk-platform-tools
sudo chown "$SETUP_USER":"$SETUP_USER" /opt/android-sdk/ -R

sdkmanager "platforms;android-$sdk_version" "build-tools;$sdk_version.0.0" "tools"
sdkmanager "system-images;android-$sdk_version;aosp_atd;x86_64"

avdmanager --verbose create avd --force --name "${emu_device}_api${sdk_version}_aosp" --package "system-images;android-$sdk_version;aosp_atd;x86_64" --device "$emu_device"

unset sdk_version
unset emu_device
