#!/bin/bash

source "../utils.sh"

unzip -q -o "$SETUP_HOME_DIR/.themes/*.zip" -d "$SETUP_HOME_DIR/.themes"
tar --xz -xf "$SETUP_HOME_DIR/.icons/*.tar.xz" -C "$SETUP_HOME_DIR/.icons"

for theme in "$SETUP_HOME_DIR/.themes/"*/; do
    sudo ln -s "$SETUP_HOME_DIR/.themes/$theme" /usr/share/themes/
done
