#!/bin/bash

source "../utils.sh"

trash_dirs=(
    Desktop
    Documents
    Downloads
    Music
    Pictures
    Public
    Templates
    Videos
    .i3
    .config/dunst
    .config/ranger
    .config/Kvantum
)
for dir in "${trash_dirs[@]}" ; do 
    fmt::msg "Cleaning up junk dir: $dir"
    rm "$SETUP_HOME_USER/${dir:?}" -rf
done
unset trash_dirs

bloat=(
    clipit
    conky
    conky-i3
    dmenu-manjaro
    lxappearance
    manjaro-i3-settings
    manjaro-ranger-settings
    manjaro-zsh-config
    xdg-desktop-portal-gnome
    xfce-terminal
    xfce4-notifyd
    xfce4-power-manager
)

for package in "${bloat[@]}" ; do
    uninst "$package"
done
unset bloat

