#!/bin/bash

trash_dirs=(
    Desktop
    Documents
    Downloads
    Music
    Pictures
    Public
    Templates
    Videos
    .i3
    .config/dunst
    .config/ranger
    .config/Kvantum
)
for dir in "${trash_dirs[@]}" ; do 
    log_msg "Cleaning up junk dir: $dir"
    rm -rf -- "$SETUP_HOME_DIR/${dir:?}"
done
unset trash_dirs

bloat=(
    bmenu
    clipit
    conky
    conky-i3
    dmenu-manjaro
    manjaro-application-utility
    manjaro-hello
    manjaro-i3-settings
    manjaro-ranger-settings
    manjaro-zsh-config
    palemoon
    pamac-cli
    pamac-gtk
    xdg-desktop-portal-gnome
    xfce-terminal
    xfce4-notifyd
    xfce4-power-manager
)

for package in "${bloat[@]}" ; do
    uninst "$package"
done
unset bloat
