#!/bin/bash

source "../utils.sh"

if test::installed "diff-so-fancy"; then
    sudo git clone https://github.com/so-fancy/diff-so-fancy /opt/diff-so-fancy
    sudo chmod +x /opt/diff-so-fancy/diff-so-fancy
    sudo ln -s /opt/diff-so-fancy/diff-so-fancy /usr/local/bin/diff-so-fancy
fi

