#!/bin/bash

pkgs=(
    texlive-binextra
    texlive-latexextra 
    texlive-langextra 
    texlive-langcyrillic 
    texlive-luatex
    texlive-fontsextra 
    texlive-bibtexextra
    texlive-science
    texlive-xetex
)
inst "${pkgs[@]}" 
unset pkgs

log::msg "Compiling cyrillic fonts..."
if mktextfm larm1000 > /dev/null 2>&1 ; then
    log::suc "Successfully compiled cyrillic fonts"
else
    log::err "Failed to compile cyrillic fonts"
    log::err "Make sure to run mktextfm again manually"
fi

