#!/bin/bash

source "../utils.sh"

pkgs=(
    texlive-latexextra 
    texlive-langextra 
    texlive-langcyrillic 
    texlive-fontsextra 
    texlive-bibtexextra
    texlive-science
)

inst $@ "${pkgs[@]}" 

fmt::msg "Compiling cyrillic fonts..."
if mktextfm larm1000 > /dev/null 2>&1 ; then
    fmt::suc "Successfully compiled cyrillic fonts"
else
    fmt::err "Failed to compile cyrillic fonts"
    fmt::err "Make sure to run mktextfm again manually"
fi

