#!/bin/bash

# FIXME 
# Package is present in repositories, e.g. for Arch:
# Currently it does not build for kernels 6.11+
# inst_aur lenovolegionlinux-dkms-git

# Temp compilation fix until packages are updated
repo_dir=/opt/LenovoLegionLinux
ensure_user_owned_dir "$repo_dir"
git_clone_or_pull https://github.com/johnfanv2/LenovoLegionLinux.git "$repo_dir"
pushd "$repo_dir" || return
cd ./kernel_module || return
make
sudo make dkms
popd || return
unset repo_dir
