#!/bin/bash

# inst_aur g810-led-git 

# Temp compilation fix until AUR package is updated
repo_dir=/opt/g810-led
sudo_git_clone_or_pull https://github.com/MatMoul/g810-led.git "$repo_dir"
pushd "$repo_dir" || return
if ! grep -q '#include <cstdint>' src/helpers/help.h; then
    sudo sed -i '/#include <iostream>/a #include <cstdint>' src/helpers/help.h
fi
sudo make bin # for hidapi
sudo make bin LIB=libusb # for libusb
sudo make install
popd || return

sudo cp -f /etc/g810-led/samples/all_green /etc/g810-led/profile
unset repo_dir
