#!/bin/bash

source "../utils.sh"

inst $@ \
    retroarch \
    retroarch-assets-ozone \
    libretro-mame \
    libretro-mesen \
    libretro-nestopia \
    libretro-picodrive

inst_aur libretro-fbneo

# Download GLSL shaders (as root as it is global install)
git clone https://github.com/libretro/glsl-shaders /usr/share/libretro/shaders/glsl-shaders

