#!/bin/bash

inst tmux 

# Plugin support
tpm_dir="$SETUP_HOME_DIR/.tmux/plugins/tpm"
git_clone_or_pull https://github.com/tmux-plugins/tpm "$tpm_dir"
log_msg "Installing tmux plugins..."
TMUX_PLUGIN_MANAGER_PATH=${SETUP_HOME_DIR}/.tmux/plugins "$tpm_dir/scripts/install_plugins.sh"
log_msg "tmux plugins installed"
unset tpm_dir
