#!/bin/bash

source "../utils.sh"

if test::installed virtualbox ; then
    msg "VirtualBox already installed. Exiting..."
    return
fi

source ./linux-headers_arch
inst virtualbox virtualbox-host-dkms

sudo modprobe vboxdrv vboxnetadp vboxnetflt

