#!/bin/bash

# Check if yay is already available in the repository
if ! inst_silent yay ; then
    inst base-devel binutils
    yaydir=/opt/yay
    ensure_user_owned_dir "$yaydir"
    git_clone_or_pull https://aur.archlinux.org/yay-bin.git "$yaydir"
    pushd "$yaydir" || (std_err "failed to create installation directory for yay: $yaydir" && return)
    makepkg -si --noconfirm --needed
    popd || return
fi
