#!/bin/bash

inst zsh

if [ -e "$SETUP_HOME_DIR/.zshrc" ] && [ ! -L "$SETUP_HOME_DIR/.zshrc" ]; then
    rm -f "$SETUP_HOME_DIR/.zshrc"
fi

omz_dir="$SETUP_HOME_DIR/.oh-my-zsh"
log_msg "Installing/updating oh-my-zsh"
git_clone_or_pull https://github.com/ohmyzsh/ohmyzsh.git "$omz_dir" --depth 1

zinit_dir="$SETUP_HOME_DIR/.zinit/zinit.git"
log_msg "Installing/updating zinit"
git_clone_or_pull https://github.com/zdharma-continuum/zinit.git "$zinit_dir" --depth 1

if is_android ; then
    chsh -s zsh
else
    sudo usermod --shell "$(which zsh)" "$SETUP_USER"
fi
