#!/bin/bash

profile=${AUTORANDR_CURRENT_PROFILE:-$1}

notify-send -i display "Display profile" "$profile"

feh --bg-fill /usr/share/backgrounds/wp.png

killall -9 start_conky
~/.config/conky/start_conky 

