#!/bin/bash

conky_cfg=~/.config/conky
conky -c $conky_cfg/side.conf -d
conky -c $conky_cfg/weather.conf -d

conky_task_conf=$conky_cfg/task.conf
if [ ! -f $conky_task_conf ]; then
    touch $conky_task_conf
fi
conky -c $conky_task_conf

tshadow=~/.task/.shadow
if [ ! -f $tshadow ]; then
    exit 1
fi

to_exec="$conky_cfg/conky-taskw.py"
echo "monitoring: $tshadow"
echo "executing on change: $to_exec"
echo $tshadow | entr -s "echo 'entr pinged' && $to_exec"
